name: CD

on: 
  push:
    branches: ["release"]
  
  workflow_dispatch:
  
jobs:
  CD:
    runs-on: ubuntu-latest
    
    steps:
    
      
      - name: Configure SSH Google Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/google.cloud.key
          chmod 600 ~/.ssh/google.cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google.cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}         

      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'corretto'
          cache: maven
        
        
      - name: Run the tests
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build the application
        run: mvn _B -f pom.xml clean install -Dmaven.test.skip=true
      - name: Deploy the application
        run: /usr/bin/java-jar -Dserver.port=8080/
